[package]
name = "task_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
inotify = "0.11.0"
chrono = "0.4.38"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"